services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      # Config de KRaft (Modo Confluent)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      
      # Config Clave
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'

      # Config de Log y Cluster ID
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kafka-logs'
      
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'